---
- hosts: local
  connection: local
  remote_user: root
  become: yes
  gather_facts: no
  vars_files:
    - awscreds.yml
  tasks:
    - name: create a security group in us-east-1
      ec2_group:
        name: webserver
        vpc_id: "vpc-0995fc576a174e53e"
        description: Webserver ec2 security group
        aws_access_key: "{{aws_id}}"
        aws_secret_key: "{{aws_key}}"
        region: "{{aws_region}}"
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
          - proto: tcp
            ports:
            - 443
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 443
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 172.31.0.0/16
      register: sg
    - debug: var=sg
    - name: New ec2 creation
      ec2:
        key_name: webserver
        aws_access_key: "{{aws_id}}"
        aws_secret_key: "{{aws_key}}"
        region: "{{aws_region}}"
        image: ami-002070d43b0a4f171
        wait: yes
        count: 1
        assign_public_ip: yes
        instance_type: t2.micro
        vpc_subnet_id: "subnet-0039f20df965c9b7a"
        group_id: "{{ sg.group_id }}"

